### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by awambua** [sh0nk/matplotlib4j#40]
xception in thread "main" com.github.sh0nk.matplotlib4j.PythonExecutionException: Python execution error: Traceback (most recent call last):
  File "*****", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

	at com.github.sh0nk.matplotlib4j.PyCommand.command(PyCommand.java:85)
	at com.github.sh0nk.matplotlib4j.PyCommand.execute(PyCommand.java:105)
	at com.github.sh0nk.matplotlib4j.PlotImpl.show(PlotImpl.java:184)
	at Main.main(Main.java:120)

**Comment by sh0nk** [comment]
@awambua 
Oh, for convenience, this library depends on numpy as well. You can install numpy in your python. I'll update the README. Thanks.
